### ISSUE TITLE
bootstrap 變數檔設定

### ISSUE THREAD

**Issue by hyxfish27** [hyxfish27/AttackOnGame#27]
需要將 `src/assets/_variables.scss` 裡面的參數調整為此次專案的規格

範疇：
color
其他待補

**Comment by eee317** [comment]
已發PR
https://github.com/hyxfish27/AttackOnGame/pull/31

**Comment by eee317** [comment]
已合併到 main https://github.com/hyxfish27/AttackOnGame/pull/34
