### ISSUE TITLE
首頁切版(請求支援）

### ISSUE THREAD

**Issue by eee317** [hyxfish27/AttackOnGame#45]
- [x] 活動、店家卡片需元件化並串接 API (感謝 Kami 大大協助

做完這兩個就可以 close 這張 issue 了

- [x] 1.這顆按鈕的行為，要往下滑下一個區塊

<img width="142" alt="image" src="https://github.com/hyxfish27/AttackOnGame/assets/38075054/668453b0-1059-41dd-9428-d119d9913044">

- [x] 2.最後一格切版

<img width="560" alt="image" src="https://github.com/hyxfish27/AttackOnGame/assets/38075054/efa6a299-6f72-444e-8ab0-1716f63448a9">

**Comment by ML-Kami** [comment]
@eee317 你做了嗎

**Comment by eee317** [comment]
目前首頁只有先切了兩個區塊（已回 dev)
@ML-Kami  還沒全部完成，雖然目前核心的頁面都先切了，但是結帳頁那邊 JS 操作上會有問題
所以首頁目前還是維持現在的畫面，如果你有時間的話，可以考慮接續完成首頁其它區塊🥹 （萬分感謝（跪謝
我會先回去處理這支[ issue ](https://github.com/hyxfish27/AttackOnGame/issues/62)

**Comment by ML-Kami** [comment]
這樣算做完了嗎

**Comment by eee317** [comment]
感謝大大支援～已關閉 issue
