### ISSUE TITLE
navbar 登入後的選單狀態

### ISSUE THREAD

**Issue by eee317** [hyxfish27/AttackOnGame#52]
**需完成的核心功能**
角色登入後，點選按鈕進到對應的後台畫面

**玩家登入後**
點選按鈕需要有下拉選單：會員資料編輯、活動管理

**店家登入後**
點選按鈕需有下拉選單：會員資料編輯、活動管理

實作困難：navbar 那層的元件目前不確定怎麼取得現在登入的角色，有在想是不是可以使用 pinia 裡面存的資料

可能需要異動 Layout.vue 的這段程式碼
<img width="563" alt="image" src="https://github.com/hyxfish27/AttackOnGame/assets/38075054/d21602b0-27fa-4cfb-925e-f2e056076d5f">

**Comment by Berutorion** [comment]
completed
