### ISSUE TITLE
切版navbar, footer, 頁籤小圖

### ISSUE THREAD

**Issue by eee317** [hyxfish27/AttackOnGame#55]
- [x] navbar 切版
- [x] 頁籤小圖
- [x] footer(感謝 Kami大大完成）

**頁籤小圖**
目前是 vite logo （如截圖），需要換成我們自己的 LOGO
實作方式：
1. 在 public 資料夾裡面上傳我們自己的檔案，圖片比例須 1:1
2. 更換 index.html 裡面的第 5 行 href 的值，換成我們在 public 資料夾的圖檔名稱就可以了
<img width="169" alt="image" src="https://github.com/hyxfish27/AttackOnGame/assets/38075054/5afcd71a-7920-46e0-b347-57b1ce657782">

**Comment by ML-Kami** [comment]
@eee317 只能先領footer

**Comment by ML-Kami** [comment]
ico的地方完成
