### ISSUE TITLE
美化玩家用戶表單（請求支援）

### ISSUE THREAD

**Issue by eee317** [hyxfish27/AttackOnGame#96]
由於店家那邊頁面缺很多
實在來不及美化這右邊的項目，再麻煩有空的大大們接手（跪謝
![image](https://github.com/hyxfish27/AttackOnGame/assets/38075054/0a654068-c808-47a8-a1c2-aa1635e2ec75)

**Comment by ML-Kami** [comment]
我這樣算做完了嗎
